spring:
  application:
    name: loansystem
  datasource:
    url: jdbc:mysql://localhost:3306/loansystem
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  output:
    ansi:
      enabled: always